elm-make src/HelloWorld1.elm --output HelloWorld1.html
elm-make src/HelloWorld2.elm --output HelloWorld2.html
elm-make src/HelloWorld3.elm --output HelloWorld3.html
elm-make src/HelloWorld4.elm --output HelloWorld4.html
elm-make src/FibonacciBars.elm --output FibonacciBars.html
elm-make src/MouseSignals1.elm --output MouseSignals1.html
elm-make src/MouseSignals2.elm --output MouseSignals2.html
elm-make src/MouseSignals3.elm --output MouseSignals3.html
elm-make src/WindowSignals1.elm --output WindowSignals1.html
elm-make src/WindowSignals1.elm --output WindowSignals1.js
elm-make src/EyesView.elm --output EyesView.html
elm-make src/Eyes.elm --output Eyes.html
elm-make src/TimeSignals.elm --output TimeSignals.html
elm-make src/DrawCircles.elm --output DrawCircles.html
elm-make src/DelayedMousePositions.elm --output DelayedMousePositions.html
elm-make src/DelayedCircles.elm --output DelayedCircles.html
elm-make src/CirclesView.elm --output CirclesView.html
elm-make src/Circles.elm --output Circles.html
elm-make src/CalculatorView.elm --output CalculatorView.html
elm-make src/CalculatorViewTest1.elm --output CalculatorViewTest1.html
elm-make src/Calculator.elm --output Calculator.html
elm-make src/KeyboardSignals1.elm --output KeyboardSignals1.html
elm-make src/KeyboardSignals2.elm --output KeyboardSignals2.html
elm-make src/KeyboardSignals3.elm --output KeyboardSignals3.html
elm-make src/KeyboardSignals4.elm --output KeyboardSignals4.html
elm-make src/Paddle.elm --output Paddle.html
elm-make src/TicTacToe.elm --output TicTacToe.html
elm-make src/Snake.elm --output Snake.html
elm-make src/SnakeView.elm --output SnakeView.html
elm-make src/SnakeRevisited.elm --output SnakeRevisited.html
